meroot: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  overview/intro: overview/01-introduction.md

plugins:
  - accordion
  - tabs
  - hints
  - code-block-copy
  - mermaid-gb
  - swagger
  - expandable-chapters
  - flexible-alerts
  - edit-link

pluginsConfig:
  edit-link:
    base: https://github.com/pheme-docs/docs/edit/main
    label: Edit this page
  swagger:
    path: reference/api.yaml
  flexible-alerts:
    style: callout
    comment:
      label: Comment
      icon: info
      className: info
    tip:
      label: Tip
      icon: fas fa-lightbulb
      className: tip
    warning:
      label: Warning
      icon: fas fa-exclamation-triangle
      className: warning
    danger:
      label: Danger
      icon: fas fa-times-circle
      className: danger 
